spring.application.name=mentorat-platform
server.port=${SERVER_PORT:8081}

gemini.api.key=${GEMINI_API_KEY:}

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=